
spring:
  redis:
    host: 139.9.225.187
    port: 6379
    password: ZL_Qwert321.
    database: 3
    ssl: false
  datasource:
    url: jdbc:mysql://139.9.225.187:3306/sk?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: ZL_Qwert321.
#  data:
#    mongodb:
##      host: 192.168.0.109
##      port: 27017
##      username: root
##      password: root
#      uri: mongodb://root:root@192.168.0.110:27017/?authSource=admin
#      database: test

