
spring:
  redis:
    host: 116.63.188.215
    port: 6379
    password: Qwert321
    database: 3
    ssl: false
  datasource:
    url: jdbc:mysql://127.0.0.1/sk?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: root
#  data:
#    mongodb:
##      host: 192.168.0.109
##      port: 27017
##      username: root
##      password: root
#      uri: mongodb://root:root@192.168.0.110:27017/?authSource=admin
#      database: test

